### ISSUE TITLE
Pressing the "Start" button for all daemons crashes SCP.

### ISSUE THREAD

**Issue by klonos** [WPN-XM/WPN-XM#353]
This is similar to #298 but that issue is now fixed (SCP 0.8.1).

1. Start SCP.
2. Right click the tray icon and select "Start All" -> all daemons start fine.
3. Either right click the tray icon and select "Stop All" or open the SCP and hit the red "Stop" button -> all daemons stop fine.
4. Right click the tray icon and select "Quit"
5. Start SCP.
6. Hit the green "Start" button -> CRASH!!!

**Comment by klonos** [comment]
Filed #354 because I still would not get the PostgreSQL entry in the SCP. Adding the entry in the .ini fixed this issue here!?!

**Comment by jakoch** [comment]
Yes, the same issue. Fixed by https://github.com/WPN-XM/WPN-XM/commit/7f856712f68303d95e3b1e340d5908588ab4f85b

**Comment by Lartza** [comment]
This crash still happens for me in 0.8.2, I'll investigate more when I get back home and file a couple of bugs maybe then... (MariaDB won't start either, possibly after the crash only)

**Comment by jakoch** [comment]
Hmm.. :(
> I'll investigate more when I get back home and file a couple of bugs 

This would be cool and i thank you for testing and reporting in advance.
